version: '3'
services:
    web:
        build: 
            context: .
            args:
                - APP=${APP}
        environment: 
            - ENV=development
        ports:
            - 8000:8000
