version: '3'
services:
    web:
        build: 
            context: .
            args:
                - APP=${APP}
        environment: 
            # - ENV=development
            - ENV=staging
            - TEST_NAME=gr
            - TEST_USERS=6
        ports:
            - 8000:8000
