
services:
  otree:
    build:
      context: ./${APP}
      dockerfile: ../otree.Dockerfile
    depends_on:
      db:
        condition: service_healthy
      cache:
        condition: service_healthy
    ports:
      - 80:8000
      - 8000:8000
    environment:
      - DATABASE_URL=postgres://postgres:otree@db/django_db
      - OTREE_ADMIN_PASSWORD=otreee
      - OTREE_AUTH_LEVEL=STUDY
      - OTREE_PRODUCTION=1
      - REDIS_URL=redis://redis:6379
  cache:
    image: redis:alpine
    restart: always
    healthcheck:
      test: ["CMD", "redis-cli", "ping"]
      interval: 1s
      timeout: 3s
      retries: 30
  db:
    image: postgres:alpine
    restart: always
    healthcheck:
      test: ["CMD", "pg_isready", "-U", "postgres"]
      interval: 1s
      timeout: 3s
      retries: 30
    environment:
      - POSTGRES_DB=django_db
      - POSTGRES_PASSWORD=otree
