version: '3'
services:
    web:
        build: 
            context: .
            args:
                - APP=${APP}
        environment: 
            - ENV=staging
            - TEST_NAME=${TEST_NAME}
            - TEST_USERS=${TEST_USERS}
        ports:
            - 8000:8000
