version: '3'

services:
    otree:
        build: ./otree
        environment:
            - REDIS_URL=redis://redis:6379
            - DATABASE_URL=postgres://postgres:otreee@db:5432/django_db
            - OTREE_ADMIN_PASSWORD=otreee
            - OTREE_PRODUCTION=1
            - OTREE_AUTH_LEVEL=STUDY
            - API_KEY=cdH1Oi0D1AzuYEKCkKxnsYJuzhr3yvGMkJVfZi0DbaFgiurUWRPVqDL4eqBuNRNc
        ports:
            - 8000:8000
        depends_on: 
            - uploader
            - redis
            - db
        restart: always
    otree_consent:
        build: ./otree_consent
        environment:
            - REDIS_URL=redis://redis:6379
            - DATABASE_URL=postgres://postgres:otreee@db2:5432/django_db
            - OTREE_ADMIN_PASSWORD=otreee
            - OTREE_PRODUCTION=1
            - OTREE_AUTH_LEVEL=STUDY
        ports:
            - 8001:8001
        depends_on: 
            - redis
            - db2
        restart: always
    uploader:
        build: ./uploader
        environment:
            - API_KEY=cdH1Oi0D1AzuYEKCkKxnsYJuzhr3yvGMkJVfZi0DbaFgiurUWRPVqDL4eqBuNRNc
            - UPLOADER_SECRET=6bqVEaFhJ5YTXbJh8jiwzQkvExUbsRFtczdIJqrmLQyltbDEq6HQ8IEfbKYdTOSs
        ports:
            - 3000:3000
        restart: always
    redis:
        image: "redis:alpine"
    db:
        image: "postgres:alpine"
        restart: always
        environment:
            - POSTGRES_DB=django_db
            - POSTGRES_PASSWORD=otreee
    db2:
        image: "postgres:alpine"
        restart: always
        environment:
            - POSTGRES_DB=django_db
            - POSTGRES_PASSWORD=otreee