version: '3'
services:
    otree:
        build: ./otree
        environment:
            - REDIS_URL=redis://redis:6379
            - DATABASE_URL=postgres://postgres:otreee@db:5432/django_db
            - OTREE_ADMIN_PASSWORD=otreee
            - OTREE_PRODUCTION=1
            - OTREE_AUTH_LEVEL=STUDY
        ports:
            - 8000:8000
        depends_on: 
            - uploader
            - redis
            - db
        restart: always
    uploader:
        build: ./uploader
        ports:
            - 3000:3000
        volumes: 
            - ./uploader:/usr/src/app
            - /usr/src/app/node_modules
    redis:
        image: "redis:alpine"
    db:
        image: "postgres:alpine"
        restart: always
        environment:
            - POSTGRES_DB=django_db
            - POSTGRES_PASSWORD=otreee